version: "2"

services:
  postPostgresDB:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: on-failure
    volumes:
      - ./post-init:/docker-entrypoint-initdb.d

  userPostgresDB:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: on-failure
    volumes:
      - ./user-init:/docker-entrypoint-initdb.d

  user-service:
    build: ./user
    restart: on-failure
    environment:
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=postgres
      - DATASOURCE_URL=jdbc:postgresql://userPostgresDB:5432/postgres
    depends_on:
      - userPostgresDB
    ports:
      - "8081:8081"

  post-service:
    build: ./post
    restart: on-failure
    environment:
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=postgres
      - DATASOURCE_URL=jdbc:postgresql://postPostgresDB:5432/postgres
    depends_on:
      - postPostgresDB
    ports:
      - "8082:8082"

